on:
  push

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan brokencrystals Website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://brokencrystals.com/'
